### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rahulreddyv** [spadarian/docblock-python#23] opened 2018-10-28 11:05 UTC
[Enter steps to reproduce:]

1. I just tried to create a class docstring from the menu of right click. It froze!!!

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [docblock-python](https://github.com/spadarian/docblock-python) package 0.10.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/himavarsha/.atom/packages/docblock-python/lib/docblock-python.js:327

RangeError: Maximum call stack size exceeded
    at /packages/docblock-python/lib/docblock-python.js:327:14
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
    at /packages/docblock-python/lib/docblock-python.js:340:22
    at Object.find_init (/packages/docblock-python/lib/docblock-python.js:345:9)
```

### Commands

```
     -0:18.9.0 core:close (atom-pane.pane.active)
     -0:08.0 docblock-python:generate_docblock (span.syntax--entity.syntax--name.syntax--type.syntax--class)
```

### Non-Core Packages

```
atom-django 0.3.2 
autocomplete-python 1.10.9 
busy-signal 1.4.3 
docblock-python 0.10.0 
docker 0.8.0 
Hydrogen 2.5.1 
intentions 1.1.5 
linter 2.0.0 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
platformio-ide-terminal 2.8.4 
python-indent 1.1.5 
python-isort 0.0.7 
react 0.18.0 
script 3.18.1 
teletype 0.13.3 
```

**Comment by SKalt** [comment] 2018-11-19 13:30
@rahulreddyv, does this error persist into v0.11.0?

**Comment by spadarian** [comment] 2018-11-26 02:10
I'm closing this issue because there is not enough information to reproduce it.

**Closed by spadarian** 2018-11-26 02:10 UTC
Labels: wontfix
